Private Mode View/Read Challenge flag and signature authentication
trufnetwork/kwil-js pull request #91
Opened 2024-09-25 02:26 UTC by tydangelo18

The feature creates a challenge flag in messages passed from client to Kwil for view/read actions. The message with the challenge is signed and sent to Kwil for authentication.

2024-09-25 17:06 UTC, KwilLuke requested changes
Good start. Still some items needed

- The NodeKwil / Webkwil call implmenetations are pretty convoluted. Please refactor to clearly handle when kwild auth, kwild noauth, and kgw auth happen.
- Only call the healthcheck endpoint on the first call request. Kwil-js should remember what it is talking to.
- Make sure that you are not unnecessarily modifying public interfaces (e.g. GenericResponse).
- Some new interfaces are needed / need to be split up.
- Add a test for when kwild is in private mode to make sure that the signature is being created?
- Remove console logs and unusued imports.

2024-09-25 17:06 UTC, KwilLuke commented on src/api_client/client.ts
> +import { Result } from 'ethers';
I think you can remove this.

2024-09-25 17:06 UTC, KwilLuke commented on src/api_client/client.ts
> +  protected async healthModeCheck(): Promise<GenericResponse<String>> {
Nit: change this name to match the naming conventions for other protected methods in the `Client` class:

E.g.

```suggestion
  protected async healthCheckClient(): Promise<GenericResponse<String>> {
```

2024-09-25 17:06 UTC, KwilLuke commented on src/core/resreq.ts
> +  authCode?: number;
A problem you have here is that `GenericResponse` is an interface that is used in the function signature for many of the public methods in kwil-js.

Although it is optional, we don't want `authCode` to appear as a possible method on every single kwil-js method. For example:

```javascript
const res = await kwil.listDatabases();

res.authCode
// ^in the context of `listDatabases();` authCode makes no sense
```


What I think you can do:
In `client.ts`, return the error code on `GenericResponse.data.error`. Given that `error` is a field on the `JsonRPCResponse` interface, you already have a space that you can return the error code in the `GenericResponse` interface. You don't need to add the `authCode` property.

2024-09-25 17:06 UTC, KwilLuke commented on src/api_client/client.ts
> +    }
HERE: Rather than passing `errorCode` to `authCode`, you can just return it with `data.result.error`

2024-09-25 17:06 UTC, KwilLuke commented on src/auth/auth.ts
> +    const sig = await bytesToBase64(signature)
Not async, so you can remove


```suggestion
    const sig = bytesToBase64(signature)
```

2024-09-25 17:06 UTC, KwilLuke commented on src/api_client/client.ts
> +  PrivateSignature,
Can remove

2024-09-25 17:06 UTC, KwilLuke commented on MIGRATING.md
> +        identifier: Array(),
`Uint8Array` is a type in TypeScript, so I would leave this as is. It more accurately describes that we are managing bytes than some arbitrary array.

2024-09-25 17:06 UTC, KwilLuke commented on src/core/auth.ts
> +}
There is already a `Signature` interface here: https://github.com/kwilteam/kwil-js/blob/3cc9faf9a06cf36ddd1ffaed8ccf3bef42299bc1/src/core/signature.ts#L6

You should use this one just so there is a single source of truth.

2024-09-25 17:06 UTC, KwilLuke commented on src/core/auth.ts
> +import { ActionBody } from './action';
Remove

2024-09-25 17:06 UTC, KwilLuke commented on src/core/message.ts
> +import { PrivateSignature } from "./auth";
Change to use the `Signature` interface here: https://github.com/kwilteam/kwil-js/blob/3cc9faf9a06cf36ddd1ffaed8ccf3bef42299bc1/src/core/signature.ts#L6

2024-09-25 17:06 UTC, KwilLuke commented on src/core/message.ts
> +    challenge?: Nillable<String>;
I would change `Nillable<string>` to `Nillable<HexString>`, just so we know what type of encoding it is.

2024-09-25 17:06 UTC, KwilLuke commented on src/core/jsonrpc.ts
>  interface EmptyRequest {
Can you define the interfaces for `ChainInfoRequest`, `ChallengeRequest`, and `HealthRequest`? The interface `EmptyRequest` is not helpful, and I am pretty sure these requests have defined shapes in kwil-db.

2024-09-25 17:06 UTC, KwilLuke commented on src/core/jsonrpc.ts
>  interface EmptyRequest {
Here are the shapes in kwil-db: https://github.com/kwilteam/kwil-db/blob/b35de9da41b14717c325f00a5159905c77eb2467/core/rpc/json/user/responses.go#L1

2024-09-25 17:06 UTC, KwilLuke commented on src/core/jsonrpc.ts
>  interface Result {
This result interface is only for the Call JSON RPC request. You should create separate interfaces for the Challenge Response and the Health Response.

2024-09-25 17:06 UTC, KwilLuke commented on src/core/enums.ts
> +  PrivateMode = -1001,
Make enums all uppercase (to match the style for other enums in this SDK).

2024-09-25 17:06 UTC, KwilLuke commented on src/core/builders.ts
> +  signature(signature: Nillable<PrivateSignature>): NonNil<PayloadBuilder>;
It feels weird that the builders now have a `signature` method and now a `signer` method. The `signer` method exists so you can execute signatures from within the builder.

What do you think of refactoring the builders so that the challenge signing happens within them (rather than chaining on the signature at the end)?

2024-09-25 17:06 UTC, KwilLuke commented on src/core/builders.ts
> +  signature(signature: PrivateSignature): Nillable<ActionBuilder>;
Same comment on the `PayloadBuilder` applies here.

2024-09-25 17:06 UTC, KwilLuke commented on src/core/auth.ts
>    uri: string;
I would change this interface to `KGWAuthInfo` or something similar so we know it is distinct.

2024-09-25 17:06 UTC, KwilLuke commented on src/core/action.ts
> +
Can you add a tsdoc comment here?

2024-09-25 17:06 UTC, KwilLuke commented on src/api_client/client.ts
> +  private handleErrorCodes<T>(
Maybe change name to smthing like `checkAuthError` so the intention is clearer.

2024-09-25 17:06 UTC, KwilLuke commented on src/builders/payload_builder.ts
> +
Fix the type casting here. `as unknown as XYZ` can create hard to debug issues in the future.

2024-09-25 17:06 UTC, KwilLuke commented on src/auth/auth.ts
> +  public async privateModeAuthenticate(signer: KwilSigner, actionBody: ActionBodyNode, challenge: string, payload: string): Promise<PrivateSignature> {
For the SDK consumer, there probably shouldn't be a difference between `authenticate` or `privateModeAuthenticate`. They should be able to just call the `authenticate` method and have it "just work", regardless of if they are using kwild or KGW.

2024-09-25 17:06 UTC, KwilLuke commented on src/client/node/nodeKwil.ts
> +    const mode = await this.healthModeCheck();
Right now, the call this healthModeCheck call will happen on every single call request.

You should store the mode somewhere on the class so that you only need to call this on the applications first call request. Each subsequent call request will know the mode and be able to proceed accordignly (kwild auth, KGW auth, or no auth altogether).

2024-09-25 17:06 UTC, KwilLuke commented on src/client/node/nodeKwil.ts
> +    if (!this.privateMode) {
Can you cleanly organize:
1) When the KGW components are handled (auth and cookie)
2) When the kwild auth components are handled
3) When the kwild no auth components are handled

Right now, this method jumps around a lot between different context-relevant behaviors, so it is hard to follow what is happening and why.

2024-09-25 17:06 UTC, KwilLuke commented on src/client/node/nodeKwil.ts
> +    delete message.data.sender;
Remove this ts-ingore and the delete. You are going to need to refactor the builder so that you can make call requests without the sender,

2024-09-25 17:06 UTC, KwilLuke commented on src/client/web/webKwil.ts
All the comments I made on NodeKwil also apply to WebKwil :)

2024-09-25 17:06 UTC, KwilLuke commented on src/client/node/nodeKwil.ts
> +    const byteChallenge = await hexToBytes(msgChallenge);
hexToBytes is not async.

2024-09-25 17:06 UTC, KwilLuke commented on src/client/node/nodeKwil.ts
> +    const base64Challenge = await bytesToBase64(byteChallenge);
bytesToBase64 is not async.

2024-09-26 20:50 UTC, tydangelo18 commented on src/builders/payload_builder.ts
> +
this self-resolved after nixing the PrivateSignature interface

2024-10-02 17:19 UTC, KwilLuke requested changes
Nice job. I really like how you split up the logic in NodeKwil and WebKwil. Super easy to read.

Main changes needed:

- `constructEncodedValues` is defined twice. This should be moved into one utility function to make future maintenance easier.
- I think there is a logic issue when you set the cookie on NodeKwil.
- Some small nits and comments

Potential Change:
- The cookie management between NodeKwil and WebKwil is forcing us to repeat a lot of code. Wdyt about moving everything into the main Kwil class and then handling the cookie in NodeKwil with a callback function? This may help future maintenance.

Before we merge:

Can you please squash all the commits and create one commit message with the `npm run commit` script? This will allow the commit message to fit in the auto-generated changelog.

Make sure to include breaking changes in the commit footer. Below is the only breaking change I found, but double check that there aren't others:
- `auth.authenticate` is now `auth.authenticateKGW`.

2024-10-02 17:19 UTC, KwilLuke commented on src/core/signature.ts
> +    challenge: string;
Challenge should be type `HexString` right?

I know it doesn't make a difference to the typescript compiler, but it is helpful for when using the interface in the future.

2024-10-02 17:19 UTC, KwilLuke commented on src/core/message.ts
> +                // description: "",
You can remove `description`. That is something that is old.

2024-10-02 17:19 UTC, KwilLuke commented on src/core/jsonrpc.ts
> +  challenge?: string;
Is `challenge` and `mode` still part of `Result`? `QueryResponse` is only used for the ad-hoc SELECT query API. I think you can remove `challenge` and `mode` from this interface.

2024-10-02 17:19 UTC, KwilLuke commented on src/builders/payload_builder.ts
> +    console.log("Payload" + tx.body.payload)
You can prob remove this :)

2024-10-02 17:19 UTC, KwilLuke commented on src/core/builders.ts
> +   * Challenge for the transaction. If this is not specified, the challenge will be retrieved from the Kwil network.
> the challenge will be retrieved from the Kwil network.

What does this mean? That if I am using the `PayloadBuilder` and I do not chain a `.challenge()`, then the builder will try to do the challenge request?

2024-10-02 17:19 UTC, KwilLuke commented on src/core/builders.ts
> +   * Signature for the transaction. If this is not specified, the signature is generated via client.
> the signature is generated via client.

What does `generated via the client` mean? The whole SDK is the client haha.

2024-10-02 17:19 UTC, KwilLuke commented on src/core/auth.ts
> +export interface PrivateModeAuthInfo {
Do you use this interface? VSCode can't find any references. If you don't use, I think you can remove.

2024-10-02 17:19 UTC, KwilLuke commented on src/core/auth.ts
> +export type AuthenticationResponse<T extends AuthenticationMode> = T extends AuthenticationMode.OPEN ? GenericResponse<BrowserAuthSuccess | NodeAuthSuccess> : Signature<BytesEncodingStatus.BASE64_ENC
Does you use this type anywhere? VSCode doesn't have references. If you don't use, you can remove.

2024-10-02 17:19 UTC, KwilLuke commented on src/api_client/client.ts
> +  protected async healthModeCheckClient(): Promise<GenericResponse<string>> {
Suggestion: Rather than checking just the mode, should `healthModeCheckClient` return everything on the `<HealthResponse>` interface? 

I am indifferent - on one hand, if we ever want get more HealthCheck info, we would probably change `healthModeCheckClient` to include the entire `HealthResponse`. On the other hand, returning `<HealthResponse>` isn't very YAGNI.

2024-10-02 17:19 UTC, KwilLuke commented on src/api_client/client.ts
> +  protected async challengeClient(): Promise<GenericResponse<string>> {
Maybe HexString for clarity?


```suggestion
  protected async challengeClient(): Promise<GenericResponse<HexString>> {
```

2024-10-02 17:19 UTC, KwilLuke commented on src/auth/auth.ts
> +    challenge?: string
I think you can remove challenge from the constructor.

2024-10-02 17:19 UTC, KwilLuke commented on src/auth/auth.ts
> +  public constructEncodedValues(preparedActions: ValueType[][]): EncodedValue[][] {
This `constructEncodedValues` method is the exact same as the `constructEncodedValues` method on action builder.

Rather than defining the same logic twice (which creates twice the maintenance burden), you should just define one utility `constructEncodedValues` function and call that in both the `auth` and `ActionBuilder`.

2024-10-02 17:19 UTC, KwilLuke commented on src/builders/action_builder.ts
> +  public constructEncodedValues(preparedActions: ValueType[][]): EncodedValue[][] {
Same comment on the `constructEncodedValues` method on Auth. I think you should just have one function and call it in both places.

2024-10-02 17:19 UTC, KwilLuke commented on src/auth/auth.ts
> +    const sig = await bytesToBase64(signature);
`bytesToBase64` is not async, so you can remove `await`.

2024-10-02 17:19 UTC, KwilLuke commented on src/auth/auth.ts
> +   * @param {KwilSigner} signer - The signer for the authentication.
`actionBody` is also a param.

2024-10-02 17:19 UTC, KwilLuke commented on src/auth/auth.ts
> +    actionBody: ActionBodyNode
The interface here should be `ActionBody`, not `ActionBodyNode`. We want this `authenticatePrivateMode` method to work in Node and browser.

2024-10-02 17:19 UTC, KwilLuke commented on src/auth/auth.ts
> +        ? this.constructEncodedValues([Object.values(actionBody?.inputs[0])])[0]
Is `this.constructEncodedValues([Object.values(actionBody?.inputs[0])])[0]` the cleanest way to do this? I know this is how we tackled it to get it working quick, but I feel like this would be quite a mind bender if someone else had to work on this.

2024-10-02 17:19 UTC, KwilLuke commented on src/auth/auth.ts
> +    const privateSignature = {
Want to add an interface here? e.g.


```suggestion
    const privateSignature: Signature<BytesEncodingStatus.BASE64_ENCODED> = {
```

2024-10-02 17:19 UTC, KwilLuke commented on src/client/node/nodeKwil.ts
> +    if (this.authMode === AuthenticationMode.OPEN) {
I think there is a logic issue here where you will end up resetting the cookie every time this is called.

2024-10-02 17:19 UTC, KwilLuke commented on src/client/node/nodeKwil.ts
> +    if (this.authMode === AuthenticationMode.OPEN) {
Let's talk live through this, but TL;DR, I think you will reset the cookie to null with every call, which will require KGW users to reauthenticate on each call.

2024-10-03 18:13 UTC, KwilLuke reviewed
Couple of minor changes on the PR still needed.

Also double check the ci.yaml. I don't think it is testing private mode like you think it is.

Once you resolve these, please feel free to squash.

2024-10-03 18:13 UTC, KwilLuke commented on src/utils/rlp.ts
> +export function analyzeVariable(val: ValueType): {
If this doesn't need to be exported, I would remove `export`.

2024-10-03 18:13 UTC, KwilLuke commented on src/core/signature.ts
> +}
Didn't we get rid of this interface because we already have the `Signature` interface?

2024-10-03 18:13 UTC, KwilLuke commented on src/core/builders.ts
> +   * @param {string} signature- The signature for the transaction.
This isn't the signature for the transaction. It is the signature for the call request. Transaction signatures are for when you want to execute a state change on Kwil, which is different.

Transaction signatures are created inside the builders. This method is for a signature that is used to authenticate for call requests.

2024-10-03 18:13 UTC, KwilLuke commented on src/client/node/nodeKwil.ts
> +    if (this.authMode === AuthenticationMode.OPEN && tempCookie) {
For readability, I would call the `if (this.authMode === AuthenticationMode.OPEN && tempCookie)` from within `kwil.call` before you call `resetCookie`.

The reason being is that when I first read through `call`, it read like there would still be the logic error where an undefined cookie would be reset on every call. However, once I clicked into `resetCookie`, I realized that wasn't the case. I think it makes more sense to move the conditional logic before calling the method, and then leaving the reset cookie logic (i.e. `this.cookie=undefined`) within the `resetCookie` method.

2024-10-03 18:13 UTC, KwilLuke commented on src/auth/auth.ts
> +    let msgChallenge = challenge.data as string;
Should we throw below this if `challenge.data` is undefined?

2024-10-03 18:13 UTC, KwilLuke commented on .github/workflows/ci.yaml
> +      - name: Run integration tests in private mode
Double check this. I don't think you are restarting kwild in private mode. It looks like you're just running the kwil-js tests again with the private mode flag set to true.

2024-10-03 18:13 UTC, KwilLuke commented on src/utils/rlp.ts
> +  const encodedArguments = inputs.length > 0 ? constructEncodedValues([inputs])[0] : [];
`constructEncodedValues([inputs])[0]` still feels fugly.

What about an approach like below. `encodeNestedArguments` is called when you need to return nested values (i.e. in the ActionBuilder). `encodeSingleArguments` can be called when you need the single `EncodedValue[]` (i.e. in auth.ts).

```typescript
function encodeNestedArguments(preparedAction: ValueType[][]): EncodedValue[][] {
  return preparedAction.map((action) => {
    return encodeSingleArguments(action);
  });
}

function encodeSingleArguments(preparedAction: ValueType[]): EncodedValue[] {
  return preparedAction.map((val) => {
    const { metadata, varType } = analyzeVariable(val);

    const metadataSpread = metadata ? { metadata } : {};

    const dataType: DataType = {
      name: varType,
      is_array: Array.isArray(val),
      ...metadataSpread,
    };

    let data: string[] | Uint8Array[] = [];

    if (Array.isArray(val) && !(val instanceof Uint8Array)) {
      data = val.map((v) => {
        return v?.toString() || '';
      });
    } else if (val instanceof Uint8Array) {
      data = [val];
    } else {
      data = [val?.toString() || ''];
    }

    return {
      type: dataType,
      data,
    };
  });
}
```

2024-10-03 22:34 UTC, KwilLuke commented on tests/kwil.test.ts
What are you trying to test here?

2024-10-10 04:02 UTC, closed without merging